function scr_weapon_stats() {
	if global.weapon = "" {	//DEVGUN
		global.weapon_type = "";
		global.weapon_damage = 5;
		global.weapon_id = "";
		global.combo = 1;
		global.roll_image_speed = 1;
		global.roll_speed = 2;
		global.weapon_sprite = "";
		global.stamina_cost = 0;
		global.idle = spr_player_twosword_idle;
		global.run = spr_player_twosword_run;
		global.stun = spr_player_twosword_stun;
		global.dead = spr_player_twosword_dead;
		global.roll = spr_player_bow_roll;
		global.rest = spr_player_twosword_dead;
		global.ladder = spr_player_twosword_ladder;
		global.attack1 = spr_player_twosword_attack1;
		global.attack2 = spr_player_twosword_attack2;
		global.attack3 = spr_player_twosword_attack3;
	} else if global.weapon = "Twohanded sword" {			//Submachine Gun
		global.weapon_type = "Two-handed";
		global.weapon_damage = 25;
		global.damage = global.weapon_damage;
		global.weapon_id = item_weapon_twosword;
		global.combo = 3;
		global.roll_speed = 2;
		global.roll_image_speed = 1;
		global.attack_speed = 0.7;
		global.attack1_hitframe = 4;
		global.attack2_hitframe = 1;
		global.attack3_hitframe = 2;
		global.stamina_cost = 10;
		global.weapon_sprite = spr_item_twohandedsword;
		global.idle = spr_player_twosword_idle;
		global.run = spr_player_twosword_run;
		global.stun = spr_player_twosword_stun;
		global.dead = spr_player_twosword_dead;
		global.roll = spr_player_twosword_roll;
		global.rest = spr_player_twosword_dead;
		global.ladder = spr_player_twosword_ladder;
		global.attack1 = spr_player_twosword_attack1;
		global.attack2 = spr_player_twosword_attack2;
		global.attack3 = spr_player_twosword_attack3;
	} else if global.weapon = "Cleaver" {			//Rifle
		global.weapon_type = "Two-handed";
		global.weapon_damage = 45;
		global.damage = global.weapon_damage;
		global.weapon_id = item_weapon_cleaver;
		global.combo = 1;
		global.roll_image_speed = 0.8;
		global.roll_speed = 2;
		global.attack_speed = 0.5;
		global.attack1_hitframe = 1;
		global.attack2_hitframe = 1;
		global.attack3_hitframe = 2;
		global.stamina_cost = 15;
		global.weapon_sprite = spr_item_twohandedcleaver;
		global.idle = spr_player_cleaver_idle;
		global.run = spr_player_cleaver_run;
		global.stun = spr_player_cleaver_stun;
		global.dead = spr_player_cleaver_dead;
		global.roll = spr_player_cleaver_roll;
		global.rest = spr_player_cleaver_dead;
		global.ladder = spr_player_cleaver_ladder;
		global.attack1 = spr_player_cleaver_attack1;
		global.attack2 = spr_player_cleaver_attack2;
		global.attack3 = spr_player_cleaver_attack3;
	} else if global.weapon = "Bow" {			//Rifle
		global.weapon_type = "Ranged";
		global.weapon_damage = 26;
		global.arrows_max = 5;
		global.damage = global.weapon_damage;
		global.weapon_id = item_weapon_bow;
		global.combo = 3;
		global.roll_image_speed = 1;
		global.roll_speed = 2;
		global.grv_full = 1;
		global.grv_n_full = 2.5;
		global.damage_multiplier = 3;
		global.bow_speed = 20;
		global.stamina_cost = 0.75;
		global.weapon_sprite = spr_item_bow;
		global.idle = spr_player_bow_idle;
		global.run = spr_player_bow_run;
		global.stun = spr_player_bow_stun;
		global.dead = spr_player_bow_dead;
		global.roll = spr_player_bow_roll;
		global.rest = spr_player_bow_dead;
		global.ladder = spr_player_bow_ladder;
		global.attack1 = spr_player_bow_attack1;
		global.attack2 = spr_player_bow_attack2;
		global.attack3 = spr_player_bow_attack3;
	}




}
